# Generated by Django 2.2.7 on 2019-11-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='comment',
        ),
    ]
