# Generated by Django 2.2.7 on 2019-11-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
