# Generated by Django 2.2.7 on 2019-11-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20191124_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Nom_Annonceur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_Number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
