# Generated by Django 2.2.7 on 2019-11-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20191130_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Nom',
            new_name='Nom_Produit',
        ),
    ]
